version: "3.9"

services:
#  db:
#    image: sqllite3
#    volumes:
#      - ./data/db:/var/lib/postgresql/data
  web:
    build: .
    command: python simple_weather/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
#    depends_on:
#      - db
