# Generated by Django 3.2.6 on 2021-09-04 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=100, verbose_name='City name')),
                ('date_year', models.DateTimeField(verbose_name='weather year')),
                ('date_month', models.DateTimeField(verbose_name='weather month')),
                ('date_day', models.DateTimeField(verbose_name='weather day')),
                ('min_temp_of_day', models.FloatField(null=True)),
                ('avg_temp_of_day', models.FloatField(null=True)),
                ('max_temp_of_day', models.FloatField(null=True)),
                ('most_common_weather', models.CharField(max_length=100)),
                ('wind_avg_velocity', models.FloatField(null=True)),
                ('wind_avg_direction', models.FloatField(null=True)),
            ],
        ),
    ]
