# Generated by Django 3.2.6 on 2021-09-05 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_check', '0002_auto_20210905_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='precipMM',
            field=models.FloatField(null=True),
        ),
    ]
